package com.kailash.fetch.ui.theme

import androidx.compose.ui.graphics.Color

//Light Mode Colors
val primaryLight = Color(0xFF79564A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFECFBF)
val onPrimaryContainerLight = Color(0xFF79564A)
val secondaryLight = Color(0xFF6D5A54)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF3DAD2)
val onSecondaryContainerLight = Color(0xFF715F58)
val tertiaryLight = Color(0xFF655F3D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE3DAB0)
val onTertiaryContainerLight = Color(0xFF655F3E)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F6)
val onBackgroundLight = Color(0xFF1E1B1A)
val surfaceLight = Color(0xFFFFF8F6)
val onSurfaceLight = Color(0xFF1E1B1A)
val surfaceVariantLight = Color(0xFFF1DFD9)
val onSurfaceVariantLight = Color(0xFF504440)
val outlineLight = Color(0xFF82746F)
val outlineVariantLight = Color(0xFFD4C3BD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF342F2E)
val inverseOnSurfaceLight = Color(0xFFF8EFEC)
val inversePrimaryLight = Color(0xFFEABDAD)
val surfaceDimLight = Color(0xFFE1D8D6)
val surfaceBrightLight = Color(0xFFFFF8F6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFBF2EF)
val surfaceContainerLight = Color(0xFFF5ECEA)
val surfaceContainerHighLight = Color(0xFFEFE6E4)
val surfaceContainerHighestLight = Color(0xFFE9E1DE)

//Dark Mode Colors
val primaryDark = Color(0xFFFFF3F0)
val onPrimaryDark = Color(0xFF46291F)
val primaryContainerDark = Color(0xFFFECFBF)
val onPrimaryContainerDark = Color(0xFF79564A)
val secondaryDark = Color(0xFFD9C1BA)
val onSecondaryDark = Color(0xFF3C2D28)
val secondaryContainerDark = Color(0xFF54433D)
val onSecondaryContainerDark = Color(0xFFC7B0A9)
val tertiaryDark = Color(0xFFFFF6D2)
val onTertiaryDark = Color(0xFF353114)
val tertiaryContainerDark = Color(0xFFE3DAB0)
val onTertiaryContainerDark = Color(0xFF655F3E)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF161312)
val onBackgroundDark = Color(0xFFE9E1DE)
val surfaceDark = Color(0xFF161312)
val onSurfaceDark = Color(0xFFE9E1DE)
val surfaceVariantDark = Color(0xFF504440)
val onSurfaceVariantDark = Color(0xFFD4C3BD)
val outlineDark = Color(0xFF9D8D89)
val outlineVariantDark = Color(0xFF504440)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE9E1DE)
val inverseOnSurfaceDark = Color(0xFF342F2E)
val inversePrimaryDark = Color(0xFF79564A)
val surfaceDimDark = Color(0xFF161312)
val surfaceBrightDark = Color(0xFF3D3837)
val surfaceContainerLowestDark = Color(0xFF110D0C)
val surfaceContainerLowDark = Color(0xFF1E1B1A)
val surfaceContainerDark = Color(0xFF231F1E)
val surfaceContainerHighDark = Color(0xFF2D2928)
val surfaceContainerHighestDark = Color(0xFF383432)







